Library/Models/Author.cs
using System.Collections.Generic;

namespace Library.Models
{
  public class Author
  {
    public Author ()
    {
      this.BookAuthors = new HashSet<BookAuthor>();
    }
     public int AuthorId { get; set; }
    public string Name { get; set; }
    public virtual ApplicationUser User { get; set; }
    public ICollection<BookAuthor> BookAuthors { get; set;}
  }
}

Library/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Mvc;
using Library.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

public class AuthorsController : Controller
  {
    private readonly LibraryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public AuthorsController(UserManager<ApplicationUser> userManager, LibraryContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userAuthor = _db.Authors.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userAuthor);
    }
    [Authorize(Policy = "RequireAdministratorRole")]
    public ActionResult Create()
    {
        ViewBag.BookId = new SelectList(_db.BookAuthors, "BookId", "Title");
        return View();
    }

    [Authorize(Policy = "RequireAdministratorRole")]
    [HttpPost]
    public async Task<ActionResult> Create(Author author, int bookId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      author.User = currentUser;
      _db.Authors.Add(author);
      if (bookId != 0)
      {
          _db.BookAuthors.Add(new BookAuthor() { BookId = bookId, AuthorId = author.AuthorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
        var thisAuthor = _db.Authors
        .Include(author => author.BookAuthors)
        .ThenInclude(join => join.Book)
        .FirstOrDefault(author => author.AuthorId == id);
        return View(thisAuthor);
    }

    [Authorize(Policy = "RequireAdministratorRole")]
    public ActionResult Edit(int id)
    {
      var thisAuthor = _db.Authors.FirstOrDefault(author => author.AuthorId == id);
      ViewBag.BookId = new SelectList(_db.Books, "BookId", "Title");
      return View(thisAuthor);
    }
    
    [Authorize(Policy = "RequireAdministratorRole")]
    [HttpPost]
    public ActionResult Edit(Author author, int BookId)
    {
      if (BookId != 0)
      {
        _db.BookAuthors.Add(new BookAuthor() { BookId = BookId, AuthorId = author.AuthorId });
      }
      _db.Entry(author).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddBook(int id)
    {
        var thisAuthor = _db.Authors.FirstOrDefault(author => author.AuthorId == id);
        ViewBag.BookId = new SelectList(_db.Books, "BookId", "Title");
        return View(thisAuthor);
    }

    [HttpPost]
    public ActionResult AddBook(Author author, int bookId)
    {
        if (bookId != 0)
        {
        _db.BookAuthors.Add(new BookAuthor() { BookId = bookId, AuthorId = author.AuthorId });
        }
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisAuthor = _db.Authors.FirstOrDefault(author => author.AuthorId == id);
      return View(thisAuthor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisAuthor = _db.Authors.FirstOrDefault(authors => authors.AuthorId == id);
      _db.Authors.Remove(thisAuthor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }

Library/Views/Authors/AddBook.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Author
@Html.ActionLink(" All Books", "Index", null, null, new { @class="btn btn-info fa fa-user-md" })
<h2>Add an Book</h2>

<h4>Add an Boook to @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.AuthorId)
  <table>
    <tr>
      <td>@Html.Label("Select Book")</td>
      <td>@Html.DropDownList("BookId")</td>
    </tr>
  </table>
  <button type="submit" class="btn btn-info fa "><i class="fa-user-plus"> Save</i></button>
}

Library/Views/Authors/Create.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Author
@Html.ActionLink(" All Authors", "Index", null, null, new { @class="btn btn-info fa fa-user" })
<h4>Add Author</h4>

@using (Html.BeginForm())
{
  <table>
    <tr>
      <td>@Html.LabelFor(model => model.Name)</td>
      <td>@Html.TextBoxFor(model => model.Name)</td>
    </tr> 
    
  </table>
  <button type="submit" class="btn btn-default fa" ><i class="fa-user-plus"> Add Author</i></button>
}

Library/Views/Authors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Author
@Html.ActionLink(" All Authors", "Index", null, null, new { @class="btn btn-info fa fa-user" })
<h2>Are you sure you want to delete this author?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <button type="submit" class="btn btn-info fa "><i class="fa-times"> Delete</i></button>
}

Library/Views/Authors/Details.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Author;

@Html.ActionLink(" View All Authors", "Index", null, null, new { @class="btn btn-info fa fa-user" })
@Html.ActionLink(" Edit", "Edit", new { id = Model.AuthorId }, new { @class="btn btn-info fa fa-edit" })
@Html.ActionLink(" Delete", "Delete", new { id = Model.AuthorId }, new { @class="btn btn-info fa fa-times" })
@Html.ActionLink(" Add Author", "AddAuthor", new { id = Model.AuthorId }, new { @class="btn btn-info fa fa-user-plus" })


<p>@Html.DisplayFor(model => model.Name)'s Details</p>
<hr />
<p>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</p>


@if(@Model.BookAuthors.Count == 0)
{
  <p>This author does not have a book(s) assigned yet.</p>
}
else
{
  <p>@Html.DisplayFor(model => model.Name)'s Book(s):</p>
  <ul>
  @if(Model.BookAuthors.Count != 0)
  {
    @foreach(var join in Model.BookAuthors)
    {
      <li>@join.Book.Title
      @Html.ActionLink("Delete", "DeleteBook", "Authors", new { joinId = @join.BookAuthorId }, new { @class="btn btn-info fa fa-times" })
      </li>
    }
  }
  </ul>
}

Library/Views/Authors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Author
@Html.ActionLink(" All Authors", "Index", null, null, new { @class="btn btn-info fa fa-user" })
<h2>Edit</h2>

<h4>Edit @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.AuthorId)
  <table>
    <tr>
      <td>@Html.LabelFor(model => model.Name)</td>
      <td>@Html.EditorFor(model => model.Name)</td>
    </tr>
    <tr>
      <td>@Html.Label("Select Book")</td>
      <td>@Html.DropDownList("BookId")</td>
    </tr>
  </table>
  <button type="submit" class="btn btn-info fa"><i class="fa-edit"> Save</i></button>
}

Library/Views/Authors/Index.cshtml
@{
  Layout = "_Layout";
}

@using Library.Models;
@model List<Library.Models.Author>;
@Html.ActionLink(" Add", "Create", null, null, new { @class="btn btn-info fa fa-user-plus" })
@Html.ActionLink(" Home", "Index", "Home", null, new { @class="btn btn-info fa fa-home" })
<h1>Authors</h1>

@if (@Model.Count == 0)
{
  <h3>No authors have been added yet!</h3>
} 
<ul>
  @foreach (Author author in Model)
  {
    <li>@Html.ActionLink($"{author.Name}", "Details", new { id = author.AuthorId })</li>
  }
</ul>